package edu.gatech.statusquo.spacetrader.driver;

import java.io.File;

import org.junit.Test;

import junit.framework.TestCase;

/**
 * The class <code>DriverTest</code> contains tests for the class {@link
 * <code>Driver</code>}
 *
 * @pattern JUnit Test Case
 *
 * @generatedBy CodePro at 11/13/12 3:03 PM
 *
 * @author Vraj Patel, Derrek Keyser
 *
 * @version $Revision$
 */
public class DriverTest extends TestCase {

    /**
     * Construct new test instance
     *
     * @param name the test name
     */
    public DriverTest(String name) {
        super(name);
    }

    /**
     * Run the void generateCoordinates() method test
     * @author Vraj Patel
     */
    @Test
    public void testGenerateCoordinates() {
        //fail("Newly generated method - fix or disable");
        // add test code here
        int arraySize = 150;
        Driver.generateCoordinates();
        
        //Checks to make sure correct amount of coordinates have been generated.
        assertEquals(Driver.PositionX.size(), arraySize);
        assertEquals(Driver.PositionY.size(), arraySize);
        
        //Checks to make sure all coordinates are >9 away from each other.
        for(int i=0; i<arraySize; i++){
            int coordinateX = Driver.PositionX.get(i);
            int coordinateY = Driver.PositionY.get(i);
            for(int j=i+1; j<arraySize; j++){
                int testCordX = Driver.PositionX.get(j);
                int testCordY = Driver.PositionY.get(j);
                int distance = (int) ((Math.pow(coordinateX - testCordX, 2)) + (Math
                        .pow(coordinateY - testCordY, 2)));
                distance = (int) (Math.sqrt(distance));
                if(distance<10){
                    fail("Coordinates were generated too close to each other!");
                }
            }
        }
        
        //Checking coordinate bounds
        for(int h=0; h<arraySize; h++){
            int cordX = Driver.PositionX.get(h);
            int cordY = Driver.PositionY.get(h); 
            if(cordX<0 || cordX>200 || cordY<0 || cordY>200){
                fail("Coordinates generated were out of the game board bounds!");
            }
            
        }
        
        
        
    }
    
    public void testGenerateNames(){
    	
    	//Check that PlanetNames.txt exists
    	File testFile = new File("PlanetNames.txt");
    	
    	if(testFile.exists() == false) {
    		fail("PlanetNames.txt doesn't exist");
    	}
    	
    	int namesArraySize = 150;
    	Driver.generateNames();
    	
    	//Check that the method generates the correct amount of names
    	assertEquals(Driver., namesArraySize);
    }
    
  
}

/*$CPS$ This comment was generated by CodePro. Do not edit it.
 * patternId = com.instantiations.assist.eclipse.pattern.testCasePattern
 * strategyId = com.instantiations.assist.eclipse.pattern.testCasePattern.junitTestCase
 * additionalTestNames = 
 * assertTrue = false
 * callTestMethod = true
 * createMain = true
 * createSetUp = false
 * createTearDown = false
 * createTestFixture = false
 * createTestStubs = false
 * methods = generateCoordinates()
 * package = edu.gatech.statusquo.spacetrader.driver
 * package.sourceFolder = Project Euler/src
 * superclassType = junit.framework.TestCase
 * testCase = DriverTest
 * testClassType = edu.gatech.statusquo.spacetrader.driver.Driver
 */