package edu.gatech.statusquo.spacetrader.presenter;

import junit.framework.TestCase;

/**
 * The class <code>CreatePlayerPresenterTest</code> contains tests for the
 * class {@link <code>CreatePlayerPresenter</code>}
 *
 * @pattern JUnit Test Case
 *
 * @generatedBy CodePro at 11/13/12 12:37 PM
 *
 * @author spencer
 *
 * @version $Revision$
 */
public class CreatePlayerPresenterTest extends TestCase {

	/**
	 * Construct new test instance
	 *
	 * @param name the test name
	 */
	public CreatePlayerPresenterTest(String name) {
		super(name);
	}

	/**
	 * Launch the test.
	 *
	 * @param args String[]
	 */
	public static void main(String[] args) {
		// add code to run tests here
	}
}

/*$CPS$ This comment was generated by CodePro. Do not edit it.
 * patternId = com.instantiations.assist.eclipse.pattern.testCasePattern
 * strategyId = com.instantiations.assist.eclipse.pattern.testCasePattern.junitTestCase
 * additionalTestNames = 
 * assertTrue = false
 * callTestMethod = true
 * createMain = true
 * createSetUp = false
 * createTearDown = false
 * createTestFixture = false
 * createTestStubs = false
 * methods = 
 * package = edu.gatech.statusquo.spacetrader.presenter
 * package.sourceFolder = SpaceTrader/src
 * superclassType = junit.framework.TestCase
 * testCase = CreatePlayerPresenterTest
 * testClassType = CreatePlayerPresenter
 */