package edu.gatech.statusquo.spacetrader.presenter;

import java.util.ArrayList;
import java.util.Collection;

import org.junit.*;

import edu.gatech.statusquo.spacetrader.model.Player;
import edu.gatech.statusquo.spacetrader.view.CreatePlayerView;
import junit.framework.TestCase;

/**
 * The class <code>CreatePlayerPresenterTest</code> contains tests for the
 * class {@link <code>CreatePlayerPresenter</code>}
 *
 * @pattern JUnit Test Case
 *
 * @generatedBy CodePro at 11/13/12 12:37 PM
 *
 * @author spencer
 *
 * @version $Revision$
 */
public class CreatePlayerPresenterTest extends TestCase {
	private Player player;
	private CreatePlayerView createPlayerView;
	private CreatePlayerPresenter createPlayerPresenter;

	/**
	 * Construct new test instance
	 *
	 * @param name the test name
	 */
	public CreatePlayerPresenterTest(String name) {
		super(name);
	}

	/**
	 * Launch the test.
	 *
	 * @param args String[]
	 */
	public static void main(String[] args) {
		// add code to run tests here
	}
	
	@Before
	public void setUp() {
		player = new Player();
		createPlayerView = new CreatePlayerView();
		createPlayerPresenter = new CreatePlayerPresenter(new CreatePlayerView(), new Player());
	}
	
    @Test
    public void checkValidityMethod() {
    	
    }
	
//	@Test
//	public void testNegativePoints() {
//		
//	}
}

/*$CPS$ This comment was generated by CodePro. Do not edit it.
 * patternId = com.instantiations.assist.eclipse.pattern.testCasePattern
 * strategyId = com.instantiations.assist.eclipse.pattern.testCasePattern.junitTestCase
 * additionalTestNames = 
 * assertTrue = false
 * callTestMethod = true
 * createMain = true
 * createSetUp = false
 * createTearDown = false
 * createTestFixture = false
 * createTestStubs = false
 * methods = 
 * package = edu.gatech.statusquo.spacetrader.presenter
 * package.sourceFolder = SpaceTrader/src
 * superclassType = junit.framework.TestCase
 * testCase = CreatePlayerPresenterTest
 * testClassType = CreatePlayerPresenter
 */